- api/src/main/java/com/michelin/ns4kafka/controllers/AdminController.java
- api/src/main/java/com/michelin/ns4kafka/services/NewNamespaceValidator.java
Currently the function createNamespace of the AdminController do 2 thing:
First it checks if we could create the new namespace
Then it creates it
We could assign the check to a service dedicated to simplify the code and future modification
> Creation of a service dedicated to the namespace verification

- api/src/main/java/com/michelin/ns4kafka/controllers/NamespaceController.java
- api/src/main/java/com/michelin/ns4kafka/security/ResourceBasedSecurityRule.java
- api/src/main/java/com/michelin/ns4kafka/security/SecurityConfig.java
- api/src/main/java/com/michelin/ns4kafka/security/local/LocalUser.java
- api/src/main/java/com/michelin/ns4kafka/security/local/LocalUserAuthenticationProvider.java
- api/src/main/resources/application.yml
- api/src/test/java/com/michelin/ns4kafka/security/LocalUserAuthenticationProviderTest.java
- api/src/test/java/com/michelin/ns4kafka/security/ResourceBasedSecurityRuleTest.java
> Added support for local Users

- api/src/main/java/com/michelin/ns4kafka/services/connect/KafkaConnectClientProxy.java
- api/src/test/java/com/michelin/ns4kafka/services/KafkaConnectClientProxyTest.java
> Fix Connect Proxy bug

- api/src/main/java/com/michelin/ns4kafka/controllers/AccessControlListController.java
- api/src/main/java/com/michelin/ns4kafka/controllers/ConnectController.java
- api/src/main/java/com/michelin/ns4kafka/controllers/NamespaceController.java
- api/src/main/java/com/michelin/ns4kafka/controllers/RoleBindingController.java
- api/src/main/java/com/michelin/ns4kafka/controllers/TopicController.java
- api/src/test/java/com/michelin/ns4kafka/controllers/AccessControlListControllerTest.java
- api/src/test/java/com/michelin/ns4kafka/controllers/ConnectControllerTest.java
- api/src/test/java/com/michelin/ns4kafka/controllers/NamespaceControllerTest.java
- api/src/test/java/com/michelin/ns4kafka/controllers/RoleBindingControllerTest.java
- api/src/test/java/com/michelin/ns4kafka/controllers/TopicControllerTest.java
> Add API server dryRun

- api/src/main/java/com/michelin/ns4kafka/controllers/AccessControlListController.java
- api/src/main/java/com/michelin/ns4kafka/controllers/ConnectController.java
- api/src/main/java/com/michelin/ns4kafka/controllers/NamespaceController.java
- api/src/main/java/com/michelin/ns4kafka/controllers/RoleBindingController.java
- api/src/main/java/com/michelin/ns4kafka/controllers/TopicController.java
- api/src/test/java/com/michelin/ns4kafka/controllers/AccessControlListControllerTest.java
- api/src/test/java/com/michelin/ns4kafka/controllers/ConnectControllerTest.java
- api/src/test/java/com/michelin/ns4kafka/controllers/NamespaceControllerTest.java
- api/src/test/java/com/michelin/ns4kafka/controllers/RoleBindingControllerTest.java
- api/src/test/java/com/michelin/ns4kafka/controllers/TopicControllerTest.java
> Add Dry Run to delete

- api/src/main/java/com/michelin/ns4kafka/controllers/AccessControlListController.java
- api/src/main/java/com/michelin/ns4kafka/models/Namespace.java
- api/src/main/java/com/michelin/ns4kafka/models/ObjectMeta.java
- api/src/main/java/com/michelin/ns4kafka/security/ResourceBasedSecurityRule.java
- api/src/main/java/com/michelin/ns4kafka/services/AccessControlEntryService.java
- api/src/main/java/com/michelin/ns4kafka/services/NamespaceService.java
- api/src/test/java/com/michelin/ns4kafka/controllers/AccessControlListControllerTest.java
- api/src/test/java/com/michelin/ns4kafka/security/ResourceBasedSecurityRuleTest.java
- api/src/test/java/com/michelin/ns4kafka/services/AccessControlEntryServiceTest.java
> Refactor ACL Controller, Service and add Tests

- api/src/main/java/com/michelin/ns4kafka/controllers/AccessControlListController.java
- api/src/main/java/com/michelin/ns4kafka/controllers/ConnectController.java
- api/src/main/java/com/michelin/ns4kafka/controllers/NamespaceController.java
- api/src/main/java/com/michelin/ns4kafka/controllers/RoleBindingController.java
- api/src/main/java/com/michelin/ns4kafka/controllers/TopicController.java
- api/src/main/java/com/michelin/ns4kafka/models/AccessControlEntry.java
- api/src/main/java/com/michelin/ns4kafka/models/Connector.java
- api/src/main/java/com/michelin/ns4kafka/models/Namespace.java
- api/src/main/java/com/michelin/ns4kafka/models/ObjectMeta.java
- api/src/main/java/com/michelin/ns4kafka/models/RoleBinding.java
- api/src/main/java/com/michelin/ns4kafka/models/Topic.java
- api/src/main/java/com/michelin/ns4kafka/validation/ConnectValidator.java
- api/src/main/java/com/michelin/ns4kafka/validation/ResourceValidator.java
- api/src/main/java/com/michelin/ns4kafka/validation/TopicValidator.java
- api/src/test/java/com/michelin/ns4kafka/controllers/AccessControlListControllerTest.java
- api/src/test/java/com/michelin/ns4kafka/controllers/ConnectControllerTest.java
- api/src/test/java/com/michelin/ns4kafka/controllers/NamespaceControllerTest.java
- api/src/test/java/com/michelin/ns4kafka/controllers/RoleBindingControllerTest.java
- api/src/test/java/com/michelin/ns4kafka/controllers/TopicControllerTest.java
- api/src/test/java/com/michelin/ns4kafka/models/AccessControlEntryTest.java
- api/src/test/java/com/michelin/ns4kafka/models/ConnectValidatorTest.java
- api/src/test/java/com/michelin/ns4kafka/models/ConnectorTest.java
- api/src/test/java/com/michelin/ns4kafka/models/NamespaceTest.java
- api/src/test/java/com/michelin/ns4kafka/models/ObjectMetaTest.java
- api/src/test/java/com/michelin/ns4kafka/models/ResourceValidatorTest.java
- api/src/test/java/com/michelin/ns4kafka/models/RoleBindingTest.java
- api/src/test/java/com/michelin/ns4kafka/models/TopicTest.java
- api/src/test/java/com/michelin/ns4kafka/models/TopicValidatorTest.java
before persisting to Storage, verify existing object is not exactly identical
> Apply persist only when resource has changed

- cli/src/main/java/com/michelin/ns4kafka/cli/ApplySubcommand.java
> Fix null error when the validation failed

- api/src/main/java/com/michelin/ns4kafka/services/KafkaConnectService.java
- api/src/main/java/com/michelin/ns4kafka/services/TopicService.java
- api/src/test/java/com/michelin/ns4kafka/services/KafkaConnectServiceTest.java
- api/src/test/java/com/michelin/ns4kafka/services/KafkaTopicServiceTest.java
#65 
Now, find all by namespace show only owned resource for topic and connect
> Change behavior of findAllByNamespace

- api/src/main/java/com/michelin/ns4kafka/controllers/AkhqClaimProviderController.java
- api/src/main/java/com/michelin/ns4kafka/services/NamespaceService.java
- api/src/test/java/com/michelin/ns4kafka/controllers/AkhqClaimProviderControllerTest.java
> Added AkhqClaimProviderController + Tests

- README.md
- api/src/main/resources/application.yml
- cli/build.gradle
- cli/src/main/java/com/michelin/ns4kafka/cli/KafkactlCommand.java
- cli/src/main/java/com/michelin/ns4kafka/cli/KafkactlConfig.java
- cli/src/main/java/com/michelin/ns4kafka/cli/services/LoginService.java
- cli/src/main/resources/application.yml
> Simplify kafkactl setup and auto create ~/.kafkactl folder

- api/src/main/java/com/michelin/ns4kafka/models/Namespace.java
- api/src/test/java/com/michelin/ns4kafka/integration/ConnectTest.java
> ConnectClusters: set empty list if no value

- api/src/main/java/com/michelin/ns4kafka/services/connect/KafkaConnectClientProxy.java
- api/src/test/java/com/michelin/ns4kafka/services/KafkaConnectClientProxyTest.java
> Fixed Host header set twice in Connect proxy

- api/src/main/java/com/michelin/ns4kafka/controllers/AccessControlListController.java
- api/src/test/java/com/michelin/ns4kafka/controllers/AccessControlListControllerTest.java
> Added get on /acls/{acl}

- api/src/main/java/com/michelin/ns4kafka/controllers/ConsumerGroupController.java
- api/src/main/java/com/michelin/ns4kafka/controllers/TopicController.java
- api/src/main/java/com/michelin/ns4kafka/logs/ConsoleLogListener.java
> Added namespace to ConsoleLogListener

- api/src/test/java/com/michelin/ns4kafka/integration/AbstractIntegrationConnectTest.java
- api/src/test/java/com/michelin/ns4kafka/integration/AbstractIntegrationTest.java
- api/src/test/java/com/michelin/ns4kafka/integration/AccessControlListTest.java
- api/src/test/resources/application-test.yml
This is a first step to increase test coverage
> Implement SASL security on TestContainers

- api/src/main/java/com/michelin/ns4kafka/services/executors/AccessControlEntryAsyncExecutor.java
- api/src/test/java/com/michelin/ns4kafka/integration/AccessControlListTest.java
> Connect Resource creates its own Consumer Group ACL

- cli/src/main/java/com/michelin/ns4kafka/cli/models/Status.java
> Display causes of error in native image

- api/src/main/java/com/michelin/ns4kafka/controllers/AccessControlListController.java
- api/src/test/java/com/michelin/ns4kafka/controllers/AccessControlListControllerTest.java
> Make AccessControlEntry spec immutable

- api/src/main/java/com/michelin/ns4kafka/services/executors/AccessControlEntryAsyncExecutor.java
- api/src/test/java/com/michelin/ns4kafka/integration/AccessControlListTest.java
> Added Transactional Id ACL when declaring KafkaStream resource

- api/src/main/java/com/michelin/ns4kafka/controllers/ApiResourcesController.java
- api/src/test/java/com/michelin/ns4kafka/integration/ApiResourcesTest.java
- api/src/test/resources/application-test.yml
- cli/src/main/java/com/michelin/ns4kafka/cli/ApiResourcesSubcommand.java
- cli/src/main/java/com/michelin/ns4kafka/cli/GetSubcommand.java
- cli/src/main/java/com/michelin/ns4kafka/cli/client/ClusterResourceClient.java
- cli/src/main/java/com/michelin/ns4kafka/cli/services/ApiResourcesService.java
- cli/src/main/resources/application.yml
> Make api-resources return allowed items only

- api/src/main/java/com/michelin/ns4kafka/services/executors/AccessControlEntryAsyncExecutor.java
- api/src/test/java/com/michelin/ns4kafka/integration/AccessControlListTest.java
> Added DESCRIBE_CONFIGS ACL to Topics Owners

- api/src/main/java/com/michelin/ns4kafka/controllers/AkhqClaimProviderController.java
- api/src/test/java/com/michelin/ns4kafka/controllers/AkhqClaimProviderControllerTest.java
> Added endpoint to support AKHQ v0.20.0

- README.md
@ThomasCAI-mlv Minimal documentation about the RapiDoc documentation
> Add RapiDoc documentation

- src/main/java/com/michelin/ns4kafka/controller/StreamController.java
- src/main/java/com/michelin/ns4kafka/service/StreamService.java
- src/main/java/com/michelin/ns4kafka/service/TopicService.java
- src/test/java/com/michelin/ns4kafka/controller/StreamControllerTest.java
- src/test/java/com/michelin/ns4kafka/service/StreamServiceTest.java
- src/test/java/com/michelin/ns4kafka/service/TopicServiceTest.java
> Delete changelog and repartition topics when deleting Kafka Streams resources

- src/main/java/com/michelin/ns4kafka/controller/AkhqClaimProviderController.java
- src/main/java/com/michelin/ns4kafka/property/Ns4KafkaProperties.java
- src/main/resources/application.yml
- src/test/java/com/michelin/ns4kafka/controller/AkhqClaimProviderControllerV3Test.java
> Add the possibility to override the support groups delimiter
