api/src/main/java/com/michelin/ns4kafka/controllers/ApiResourcesController.java
``GET /api-resources`` responds with following json : 
````json
[
{
"kind": "AccessControlEntry",
"namespaced": true,
"path": "acls",
"names": [
"acls",
"acl",
"ac"
]
},
{
"kind": "Connector",
"namespaced": true,
"path": "connects",
"names": [
"connects",
"connect",
"co"
]
},
{
"kind": "RoleBinding",
"namespaced": true,
"path": "role-bindings",
"names": [
"rolebindings",
"rolebinding",
"rb"
]
},
{
"kind": "Topic",
"namespaced": true,
"path": "topics",
"names": [
"topics",
"topic",
"to"
]
},
{
"kind": "Namespace",
"namespaced": false,
"path": "namespaces",
"names": [
"namespaces",
"namespace",
"ns"
]
}
]
````
=> New endpoint to expose available resources to kafkactl

api/src/main/java/com/michelin/ns4kafka/security/ResourceBasedSecurityRule.java, api/src/test/java/com/michelin/ns4kafka/security/ResourceBasedSecurityRuleTest.java
RoleBinding allowing access on /api/namespaces/ns/role-bindings failed to match because the ``-`` in ``role-bindings`` was not allowed in the regex
=> Fixed bug with RoleBinding allows /api/namespaces/ns/role-bindings

api/src/main/java/com/michelin/ns4kafka/models/ObjectMeta.java, api/src/main/java/com/michelin/ns4kafka/security/ResourceBasedSecurityRule.java, api/src/test/java/com/michelin/ns4kafka/integration/TopicTest.java, api/src/test/java/com/michelin/ns4kafka/security/ResourceBasedSecurityRuleTest.java
Any operation on subresource : 
- POST /api/namespaces/xxxxx/consumer-groups/`object-name`/reset
If `object-name` contained dot `.`
Those API calls would return 401 Forbidden
Fixed by : 
- adding `.` in the `namespacedResourcePattern` regex related to resource name
- adding `$` to the end of the `namespacedResourcePattern` regex
- adding Pattern annotation to the ObjectMeta name to prevent any other character
closes #85
=> 403 Forbidden when using controller methods with resource name containing . (dot)

api/src/main/java/com/michelin/ns4kafka/services/connect/KafkaConnectClientProxy.java
When ns4kafka queries kafka connect API, it keeps the original Host header which causes issues when the target endpoint is using TLS.
This fix corrects the Host header vefore contacting kafka connect
=> Added Host header when fowarding to kafka connect backends

api/src/main/java/com/michelin/ns4kafka/controllers/ApiResourcesController.java, cli/src/main/java/com/michelin/ns4kafka/cli/DeleteRecordsSubcommand.java, cli/src/main/java/com/michelin/ns4kafka/cli/FormatUtils.java, cli/src/main/java/com/michelin/ns4kafka/cli/GetSubcommand.java, cli/src/main/java/com/michelin/ns4kafka/cli/ImportSubcommand.java, cli/src/main/java/com/michelin/ns4kafka/cli/KafkactlConfig.java, cli/src/main/java/com/michelin/ns4kafka/cli/ResetOffsetsSubcommand.java, cli/src/main/java/com/michelin/ns4kafka/cli/services/FormatService.java, cli/src/main/java/com/michelin/ns4kafka/cli/services/ResourceService.java, cli/src/main/resources/application.yml
Using a very simple formatting descriptor, provide sensible defaults to display resources by Kind.
Allow the user to override the way resources are displayed
````yaml
table:
- kind: Topic
columns:
- TOPIC:/metadata/name
- RETENTION:/spec/configs/retention.ms%PERIOD
- AGE:/metadata/creationTimestamp%AGO
- CLUSTER:/metadata/cluster
- kind: Connector
display:
- TOPIC:/metadata/name
- AGE:/metadata/creationTimestamp%AGO
````
````console
user@local:/home/user$ kafkactl get topic -n ixxxmfg0
TOPIC              RETENTION  AGE                CLUSTER
namespace.topic1   23h30m     il y a 2 semaines  if4mmfg0 
namespace.topic2   23h30m     il y a 5 jours     if4mmfg0 
namespace.topic3   23h30m     il y a 5 jours     if4mmfg0 
namespace.topic4   23h30m     il y a 5 jours     if4mmfg0
namespace.topic9 …
```
=> Added configurable columns display in CLI

api/src/main/java/com/michelin/ns4kafka/services/executors/ConnectorAsyncExecutor.java
When an error occurs during Kafka Connect synchronization process, it's impossible to know which Connect cluster is the source of the error. This adds the connect cluster in logging on error
=> Improved error logging within ConnectorAsyncExecutor

api/src/main/java/com/michelin/ns4kafka/controllers/ApiResourcesController.java, api/src/main/java/com/michelin/ns4kafka/services/SchemaService.java, api/src/test/java/com/michelin/ns4kafka/services/SchemaServiceTest.java
Before that, audit log would display : 
`User xxxx created Schema test-value in namespace null on cluster null`
=> Added Namespace and Cluster to Schema resource for AuditLog

api/src/main/java/com/michelin/ns4kafka/controllers/ConnectController.java, api/src/test/java/com/michelin/ns4kafka/controllers/ConnectControllerTest.java, api/src/test/java/com/michelin/ns4kafka/integration/ConnectTest.java
=> Remove requirement for name in Kafka Connect spec.config.name

api/src/main/java/com/michelin/ns4kafka/services/SchemaService.java, api/src/test/java/com/michelin/ns4kafka/services/SchemaServiceTest.java
Currently, `kafkactl get schemas` returns the schemas name, version, id, and compatibility mode. It's great but if the namespace owns 100's of schemas, the performance is very poor.
Since ns4kafka doesn't cache registry call, it makes more sense for now to simply list the subjects names available (and nothing else)
=> Make kafkactl get schemas return only names

src/main/java/com/michelin/ns4kafka/models/Namespace.java, src/main/java/com/michelin/ns4kafka/models/quota/ResourceQuota.java, src/main/java/com/michelin/ns4kafka/models/quota/ResourceQuotaResponse.java, src/main/java/com/michelin/ns4kafka/services/ResourceQuotaService.java, src/main/java/com/michelin/ns4kafka/services/executors/UserAsyncExecutor.java, src/test/java/com/michelin/ns4kafka/integration/UserTest.java, src/test/java/com/michelin/ns4kafka/services/ResourceQuotaServiceTest.java
- Adding client quota customization
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
name: myNamespace
cluster: cluster1
spec:
kafkaUser: kafkaServiceAccount
kafkaUserQuota:
producer_byte_rate: 204800
consumer_byte_rate: 409600
```
- Fixing update user quota filtering. Update has to be performed if namespace user quota definition is different from the broker user quota
- Adding integration tests for both custom quota and quota updates
**Note**: at the beginning I was thinking of specifying the user quota like this
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
name: myNamespace
cluster: cluster1
spec:
kafkaUser: 
name: kafkaServiceAccount
producer_byte_rate: 204800
consumer_byte_rate: 409600
```
But this format would have broken the namespace unmarshalling with existing …
=> Added producer/consumer byte rate client quota customization

src/main/java/com/michelin/ns4kafka/controllers/AkhqClaimProviderController.java, src/test/java/com/michelin/ns4kafka/controllers/AkhqClaimProviderControllerV3Test.java
We decided during the v3 endpoint creation to add the same filtering on schema than on topics (see [here](https://github.com/michelin/ns4kafka/pull/297#discussion_r1258401210))
We figured out that a bug appears with LITERAL ACL because we will set the same pattern for "registry-read" role on these ACL (ex: `"^\\Qproject.topic\\E$"`). The filtering on schemas list searches literally for schema with the `project.topic` name which is incorrect because schemas will be named `project.topic-key` or `project.topic-value`
This PR fixes the issue by updating the pattern for patterns that do not contain `.*` (pattern for prefixed ACL).  Then, literal pattern `"^\\Qproject.topic\\E$"` becomes `"^\\Qproject.topic-\\E(key|value)$"`
=> Add key/value suffix for schema filtering on LITERAL ACL on v3 claim

src/main/java/com/michelin/ns4kafka/service/executor/TopicAsyncExecutor.java, src/test/java/com/michelin/ns4kafka/service/executor/TopicAsyncExecutorTest.java
When a tagged topic is deleted, it is recreated. This MR fixes that issue.
=> Fix topic with Confluent tag being recreated after deletion

src/main/java/com/michelin/ns4kafka/controller/NamespaceController.java, src/main/java/com/michelin/ns4kafka/service/AclService.java, src/main/java/com/michelin/ns4kafka/service/NamespaceService.java, src/test/java/com/michelin/ns4kafka/controller/NamespaceControllerTest.java, src/test/java/com/michelin/ns4kafka/service/NamespaceServiceTest.java
Add the possibility to find the namespace which is the owner of a topic, thanks to a given topic name.
The PR adds the `topic` query parameter in the LIST namespace API:
- if the query parameter is an empty string, the endpoint doesn't filter at all by the topic name.
- if the query parameter is not empty, the endpoint finds the namespace which is the owner of the topic. It returns no namespace if no namespace is owner of the topic (or the topic doesn't exist).
Maybe, the implementation could be 2 additional parameters, resource type and resource name, to allow the search on all types of resources (not only topics), I left it to discussion.
=> Find namespace from topic name

src/main/java/com/michelin/ns4kafka/controller/connect/ConnectClusterController.java, src/main/java/com/michelin/ns4kafka/service/AclService.java, src/main/java/com/michelin/ns4kafka/service/ConnectClusterService.java, src/main/java/com/michelin/ns4kafka/util/FormatErrorUtils.java, src/test/java/com/michelin/ns4kafka/controller/ConnectClusterControllerTest.java, src/test/java/com/michelin/ns4kafka/service/ConnectClusterServiceTest.java
For the connect cluster vault API, I simplified the `validateConnectClusterVault` method check:
- If the provided connect cluster is not found (the connect cluster does not exist or the namespace does not have the OWNER or WRITE ACL on this connect cluster), throw an "not found" error
- If the provided connect cluster is found but is missing AES config fields, throw an "no config" error. I updated the error message to be more explicit, because previously, it was confusing to display the list of other usable vault connect clusters, since the user explicitly gave the connect cluster he wants to use to vault his secrets. In any case, they can use the LIST vaults API to list the available vaults connect clusters.
I also removed the "allowed namespace" check because it was weird to provide …
=> Improve connect cluster vault error handling

.docker/resources/admin/another-namespace2.yml, README.md, src/main/java/com/michelin/ns4kafka/security/ResourceBasedSecurityRule.java, src/main/java/com/michelin/ns4kafka/security/auth/AuthenticationRoleBinding.java, src/main/java/com/michelin/ns4kafka/security/auth/AuthenticationService.java, src/test/java/com/michelin/ns4kafka/security/ResourceBasedSecurityRuleTest.java, src/test/java/com/michelin/ns4kafka/security/auth/AuthenticationInfoTest.java, src/test/java/com/michelin/ns4kafka/security/auth/AuthenticationServiceTest.java, src/test/java/com/michelin/ns4kafka/security/auth/gitlab/GitlabAuthenticationProviderTest.java, src/test/java/com/michelin/ns4kafka/security/auth/ldap/LdapAuthenticationMapperTest.java, src/test/java/com/michelin/ns4kafka/security/auth/local/LocalUserAuthenticationProviderTest.java
This PR is about reducing the size of the JWT (`access_token`) generated by the `/login` endpoint, which is then used to authenticate in other endpoints. This would heavily reduce the risk of reaching the `http.client.max-content-length` limit in the future when the namespaces number increases, and have better performance in the logging process.
Example of the current JWT roleBindings format:
`"roleBindings": [
{
"namespace": "namespace1",
"verbs": [
"GET",
"POST",
"PUT",
"DELETE"
],
"resourceTypes": [
"schemas",
"schemas/config",
"topics",
"topics/delete-records"
]
},
{
"namespace": "namespace2",
"verbs": [
"GET",
"POST",
"PUT",
"DELETE"
],
"resourceTypes": [
"schemas",
"schemas/config",
"topics",
"topics/delete-records"
]
},
{
"namespace":  "namespace3",
"verbs": [
"GET",
"POST",
"PUT", …
=> Improve JWT format with namespaces grouping

README.md, src/main/java/com/michelin/ns4kafka/service/client/schema/SchemaRegistryClient.java, src/main/java/com/michelin/ns4kafka/service/client/schema/entities/GraphQueryData.java, src/main/java/com/michelin/ns4kafka/service/client/schema/entities/GraphQueryResponse.java, src/main/java/com/michelin/ns4kafka/service/client/schema/entities/GraphQueryTopic.java, src/main/java/com/michelin/ns4kafka/service/executor/TopicAsyncExecutor.java, src/test/java/com/michelin/ns4kafka/service/executor/TopicAsyncExecutorTest.java
**1. Context**
- Currently, we have the possibility to add tags and description to a topic and ns4kafka synchronizes these information with **Confluent Cloud** catalog information (tags & description). This synchronisation is performed with the Stream Catalog REST API ([Stream Catalog documentation](https://docs.confluent.io/cloud/current/stream-governance/stream-catalog-rest-apis.html)).
- However, this API is not suited for the synchronisation because of the **500 topics limit** per call, and the fact that **there is no filter** allowing to **query only topics with a description** (though it is possible to query only topics with at least one tag). These drawbacks lead to having to query all the cluster topics 500 per 500 in order to perform the synchronization, which is quite bad for …
=> Improve catalog information synchronisation with GraphQL

README.md, src/main/java/com/michelin/ns4kafka/service/ConnectClusterService.java
@ThomasCAI-mlv No documentation about this little configuration, unless I'm wrong
=> Add documentation about encryption

src/main/java/com/michelin/ns4kafka/util/FormatErrorUtils.java, src/main/java/com/michelin/ns4kafka/validation/ResourceValidator.java, src/test/java/com/michelin/ns4kafka/model/ResourceValidatorTest.java
This PR adds a new validator "ContainsList". It checks that a field contains all the items from a list.
It helps in our case to prevent users from creating connectors on some topics by adding this validator to the topic.blacklist field.
```yaml
connectValidator:
validationConstraints:
topic.blacklist:
validation-type: ContainsList
mandatoryStrings:
- ns1.topic1
- ns1.topic2
```
Expected value 
```yaml
topic.blacklist: ns1.topic1,ns1.topic2,ns1.otherTopicToBlacklist
```
=> Add new ContainsList validator

src/main/java/com/michelin/ns4kafka/controller/topic/TopicController.java, src/main/java/com/michelin/ns4kafka/service/TopicService.java, src/test/java/com/michelin/ns4kafka/controller/TopicControllerTest.java, src/test/java/com/michelin/ns4kafka/service/TopicServiceTest.java
This PR adds the possibility to import specific unsynchronized topics from the cluster to Ns4kafka, in addition to the previous capability to import all unsynchronized topics at once.
In the endpoint POST `/topics/_/import`, the query parameter `name` can be used to specifically import one topic or multiple topics following a wildcard string.
Example: 
- `/topics/_/import?name=myTopicName` would only import the topic `myTopicName` if it exists on the cluster but is missing from Ns4kafka
- `/topics/_/import?name=*-test` would import all the unsynchronized topics matching the wildcard `*-test`
=> Add the possibility to import specific topics

src/main/java/com/michelin/ns4kafka/controller/ConnectorController.java, src/main/java/com/michelin/ns4kafka/service/ConnectorService.java, src/test/java/com/michelin/ns4kafka/controller/ConnectorControllerTest.java, src/test/java/com/michelin/ns4kafka/service/ConnectorServiceTest.java
This PR adds the possibility to import specific unsynchronized connectors from the kconnect cluster to Ns4kafka, in addition to the previous capability to import all unsynchronized connectors at once.
In the endpoint POST `/connectors/_/import`, the query parameter `name` can be used to specifically import one connector or multiple connectors following a wildcard string.
Example:
- `/connectors/_/import?name=myConnectorName` would only import the connector `myConnectorName` if it exists on the cluster but is missing from Ns4kafka
- `/connectors/_/import?name=*-test` would import all the unsynchronized connectors matching the wildcard `*-test`
=> Add the possibility to import specific connectors

src/main/java/com/michelin/ns4kafka/service/SchemaService.java
Adds ` .references(subjectResponse.references())` to `buildSchemaSpec`
Fixes #627
=> Fixed an issue for schema references on GET
